server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 # 配置Nacos地址
        server-addr: http://192.168.31.60:1111 # 配置Nacos集群地址（nginx地址，转发到nacos地址）
management:
  endpoints:
    web:
      exposure:
        include: '*'